### ISSUE TITLE
Fix repository name

### ISSUE THREAD

**Issue by gcrozariol** [paaulamessias/travelgram-html#5]
Use the [kebab-case](https://developer.mozilla.org/en-US/docs/Glossary/Kebab_case) naming convention for the repositories name. For example: `project-name-technology`. 

In the case of this repository, `travelgram-html` would be better.

**Comment by paaulamessias** [comment]
Improvement to the project name made @gcrozariol

**Comment by gcrozariol** [comment]
> Improvement to the project name made @gcrozariol

The project name still uses uppercase letters. Fix it to match the [kebab-case](https://developer.mozilla.org/en-US/docs/Glossary/Kebab_case) naming convention.
